# Generated by Django 6.0.3 on 2026-03-09 14:02

from django.db import migrations

def create_groups(apps, schema_editor):

    Group = apps.get_model("auth", "Group")

    Group.objects.get_or_create(name="Manager")
    Group.objects.get_or_create(name="Staff")
    Group.objects.get_or_create(name="Guest")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]